spring:
  application:
    name: ProdutosAPI
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console